#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../lib/xgame'

XGame('The Panda', [800,600], 70) { |screen, background, world, callbacks|

	class Panda < Rubygame::Sprites::BasicSprite
		include Rubygame::Sprites::MovingSprite
		include Rubygame::Sprites::BoundedSprite
	end

	panda = Panda.new(10,800,'panda.png')
	world.force = [0,1,{:down => 4}] # Gravity. Force of 1 down that may not take velocity above 4
	world << panda

	callbacks[Rubygame::KeyDownEvent] = lambda { |event|
			case event.key
				when Rubygame::K_ESCAPE
					throw :quit #quit when the user hits escape
				when Rubygame::K_RIGHT
					panda.go([1,nil])
				when Rubygame::K_LEFT
					panda.go([-1,nil])
				when Rubygame::K_UP
					panda.go([nil,-2])
			end
	}

	callbacks[Rubygame::KeyUpEvent] = lambda { |event|
			case event.key
				when Rubygame::K_RIGHT
					panda.stop(:right)
				when Rubygame::K_LEFT
					panda.stop(:left)
				when Rubygame::K_UP
					panda.stop(:up)
			end
	}

}
